package com.pabloriosramirez.web.api.entity;

import javax.persistence.Column;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Persons generated by hbm2java
 */
public class Person implements java.io.Serializable {

    /**
     *
     */
    @NotEmpty
    @Size(min = 1, max = 99)
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @NotEmpty
    @Size(min = 1, max = 99)
    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    public Person() {
    }

    public Person(String name, String lastName) {
        this.name = name;
        this.lastName = lastName;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public String toString() {
        return "Person{" + "name=" + name + ", lastName=" + lastName + '}';
    }

}
